Repository AHSCodingClub/CR-Soundboard, pull requests merged in 2022-10, with the labels that each got.

#2 Add Mr. Appel to the about view
  ClubDay2022/Views/AboutView.swift
Labels: enhancement

#7 Emote Updates
  ClubDay2022/Shared.swift
Labels: enhancement

#10 Add SwiftFormat, fix comments
  .swift-format
  ClubDay2022/ClubDay2022App.swift
  ClubDay2022/Models/AudioPlayer.swift
  ClubDay2022/Models/Emote.swift
  ClubDay2022/Models/ViewModel.swift
  ClubDay2022/Shared.swift
  ClubDay2022/Views/AboutView.swift
  ClubDay2022/Views/ContentView.swift
  ClubDay2022/Views/EmotesView.swift
Labels: documentation

#12 Lots More Emote Fixes
  ClubDay2022/Shared.swift
Labels: enhancement

#11 Add `relativeTo` property
  ClubDay2022/Views/SoundboardView.swift
Labels: bug

#16 Change on/off button to play/pause icon
  ClubDay2022/Views/ContentView.swift
  ClubDay2022/Views/SoundboardView.swift
Labels: enhancement
